version: "2"

services:

  web:
    image: ctftraining/huwangbei_2018_easy_tornado
    build: .
    restart: always
    environment:
      - FLAG=flag{glzjin_wants_a_girl_friend}
    ports:
      - "127.0.0.1:8081:5000"
